### ISSUE TITLE
New (python3) release for distribution packagers

### ISSUE THREAD

**Issue by UffeJakobsen** [michaelcmartin/Ophis#36] opened 2024-05-30 07:45 UTC
Hi,
Could you be persuaded to make a new release of the current HEAD - in order to get python3 support out ?

The latest release is 2.1.1 - and that is a python2 release

That would make the work for distribution packagers easier

Thanks in advance :-)

**Comment by michaelcmartin** [comment] 2024-07-12 02:16
I've been busy with other things but expect to be looping back to this project fairly soon, but this is a somewhat puzzling request:
* My most recent formal release is 2.1. Has someone else done a 2.1.1 release without actually informing me?
* Any 2.1.1 release needs me to fix #35 and ideally #34 as well; python distribution has evolved over the years and the tooling needs to be updated.

Is there something here that isn't a duplicate of those that I should be aware of?

**Comment by UffeJakobsen** [comment] 2024-07-12 15:29
thanks for your answer :-)

Sorry - the 2.1.1 is a typo from my side - it was supposed to be version 2.1

**Comment by UffeJakobsen** [comment] 2024-07-12 15:31
FYI: I found this repo that seems to have done some further development https://github.com/gardners/Ophis/

**Comment by michaelcmartin** [comment] 2024-07-13 05:03
Yeah, his work is part of 2.1, even; most of the support for the 4502/Mega65 is either directly his work or based on it. Thanks for the pointer, but it turns out he filed a PR for it here awhile back, so that stuff was on my radar 😄 

In the absence of something special, I'm going to close this as a duplicate of #35 - this project has been fallow/stable for awhile now but I was intending to loop back to it once I wrapped up my current project. Watch this space; I expect there to be some progress later this month or August or so!

**Closed by michaelcmartin** 2024-07-13 05:03 UTC

**Comment by UffeJakobsen** [comment] 2024-07-13 11:05
Thanks for the update :+1:

**Comment by michaelcmartin** [comment] 2024-07-29 01:02
Final update on this ticket: There is now a formal 2.2 release both here and at PyPI: https://pypi.org/project/ophis-asm/

**Comment by UffeJakobsen** [comment] 2024-07-29 09:29
Thank you so much :+1:
